/* Sri Tabemashou POS - Inventory, Purchase & Stock Ledger */
(function(){
const INVENTORY_KEY='inventory', LEDGER_KEY='sriTabemashouInventoryLedger', PURCHASE_KEY='sriTabemashouPurchases';
function readInventory(){try{const v=JSON.parse(localStorage.getItem(INVENTORY_KEY)||'{}');return v&&typeof v==='object'&&!Array.isArray(v)?v:{}}catch{return{}}}
function saveInventory(v){localStorage.setItem(INVENTORY_KEY,JSON.stringify(v||{}));}
function getLedger(){try{const v=JSON.parse(localStorage.getItem(LEDGER_KEY)||'[]');return Array.isArray(v)?v:[]}catch{return[]}}
function saveLedger(v){localStorage.setItem(LEDGER_KEY,JSON.stringify((v||[]).slice(-5000)))}
function getPurchases(){try{const v=JSON.parse(localStorage.getItem(PURCHASE_KEY)||'[]');return Array.isArray(v)?v:[]}catch{return[]}}
function savePurchases(v){localStorage.setItem(PURCHASE_KEY,JSON.stringify(v||[]))}
function stockInfo(r){if(!r||typeof r!=='object')return null;for(const f of ['stock','quantity','qty','currentStock','availableStock','units']){const n=Number(r[f]);if(Number.isFinite(n))return{field:f,value:n}}return null}
function getStock(r){return stockInfo(r)?.value||0}
function findKey(inv,name){const x=String(name||'').trim();if(!x)return null;if(Object.hasOwn(inv,x))return x;const l=x.toLowerCase();return Object.keys(inv).find(k=>k.toLowerCase()===l)||null}
function normalizeRecipe(menuItem){if(Array.isArray(menuItem?.ingredients)&&menuItem.ingredients.length)return menuItem.ingredients.map(i=>({name:String(i.name||i.item||'').trim(),qty:Number(i.qty??i.quantity??0)})).filter(i=>i.name&&i.qty>0);return menuItem?.name?[{name:String(menuItem.name).trim(),qty:1}]:[]}
function logMovement(m){const ledger=getLedger();ledger.push({...m,date:m.date||new Date().toISOString()});saveLedger(ledger)}
function deductInventoryForBill(bill){const inv=readInventory();if(!bill||!Array.isArray(bill.items))return{changed:false,deductions:[]};let changed=false,deductions=[];let menus=[];try{menus=JSON.parse(localStorage.getItem('sriTabemashouMenu')||'[]')}catch{}
bill.items.forEach(item=>{const menu=menus.find(m=>String(m.id)===String(item.id))||item;const recipe=normalizeRecipe(menu);const mult=Number(item.quantity??item.qty??1)||1;recipe.forEach(c=>{const key=findKey(inv,c.name);if(!key)return;const si=stockInfo(inv[key]);if(!si)return;const qty=c.qty*mult,before=si.value,after=Math.max(0,before-qty);inv[key][si.field]=after;changed=true;const entry={type:'sale',inventoryKey:key,quantity:-qty,before,after,reference:bill.billNumber||'',billNumber:bill.billNumber||''};deductions.push(entry);logMovement(entry)})});if(changed)saveInventory(inv);return{changed,deductions}}
function reverseInventoryForBill(bill,type='void'){const inv=readInventory();if(!bill||!Array.isArray(bill.inventoryDeductions))return false;let changed=false;bill.inventoryDeductions.forEach(d=>{const key=findKey(inv,d.inventoryKey);if(!key)return;const si=stockInfo(inv[key]);if(!si)return;const qty=Math.abs(Number(d.quantity)||0),before=si.value,after=before+qty;inv[key][si.field]=after;changed=true;logMovement({type,inventoryKey:key,quantity:qty,before,after,reference:bill.billNumber||'',billNumber:bill.billNumber||''})});if(changed)saveInventory(inv);return changed}
window.getPOSInventory=readInventory;window.savePOSInventory=saveInventory;window.deductInventoryForBill=deductInventoryForBill;window.reverseInventoryForBill=reverseInventoryForBill;window.inventoryLedger=getLedger;

function money(v){return '₹'+Number(v||0).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2})}
function openInventoryTab(name,btn){document.querySelectorAll('.inventory-panel').forEach(x=>x.classList.remove('active'));document.getElementById('inventory'+name.charAt(0).toUpperCase()+name.slice(1))?.classList.add('active');document.querySelectorAll('.inventory-tab').forEach(x=>x.classList.remove('active'));btn?.classList.add('active');if(name==='products')renderProducts();if(name==='purchases')renderPurchases();if(name==='movement')renderMovements()}
function openProductModal(key=''){if(typeof hasPermission==='function'&&!hasPermission('inventory.manage')){alert('You do not have permission to manage inventory.');return}const inv=readInventory(),r=key?inv[key]:{};productKey.value=key;productName.value=key;productCategory.value=r.category||'';productUnit.value=r.unit||'';productStock.value=getStock(r);productReorder.value=Number(r.reorderLevel??r.minStock??0);productCost.value=Number(r.cost||r.price||0);document.getElementById('productModal').classList.add('active')}
function closeProductModal(){document.getElementById('productModal')?.classList.remove('active')}
function openPurchaseModal(){if(typeof hasPermission==='function'&&!hasPermission('inventory.manage')){alert('You do not have permission to manage inventory.');return}const select=document.getElementById('purchaseProduct');const inv=readInventory();select.innerHTML=Object.keys(inv).map(k=>`<option value="${escapeHTML(k)}">${escapeHTML(k)}</option>`).join('');purchaseDate.value=new Date().toISOString().slice(0,10);purchaseQty.value='';purchasePrice.value='';purchaseSupplier.value='';purchaseInvoice.value='';purchaseNotes.value='';document.getElementById('purchaseModal').classList.add('active')}
function closePurchaseModal(){document.getElementById('purchaseModal')?.classList.remove('active')}
function renderProducts(){const inv=readInventory(),q=(document.getElementById('inventorySearch')?.value||'').toLowerCase(),filter=document.getElementById('inventoryLowFilter')?.value||'all',tbody=document.getElementById('productTable');if(!tbody)return;let rows=Object.entries(inv).filter(([k,r])=>{const low=Number(r.reorderLevel??r.minStock??0)>0&&getStock(r)<=Number(r.reorderLevel??r.minStock);return k.toLowerCase().includes(q)&&(filter==='all'||(filter==='low'&&low)||(filter==='ok'&&!low))});tbody.innerHTML=rows.length?rows.map(([k,r])=>{const low=Number(r.reorderLevel??r.minStock??0)>0&&getStock(r)<=Number(r.reorderLevel??r.minStock);return `<tr class="${low?'low-stock-row':''}"><td><strong>${escapeHTML(k)}</strong></td><td>${escapeHTML(r.category||'-')}</td><td>${escapeHTML(r.unit||'-')}</td><td>${getStock(r)}</td><td>${Number(r.reorderLevel??r.minStock??0)}</td><td><button class="secondary-btn" onclick="openProductModal('${escapeJS(k)}')">✏️</button> <button class="secondary-btn" onclick="adjustStock('${escapeJS(k)}')">↕️</button></td></tr>`}).join(''):'<tr><td colspan="6" style="text-align:center;padding:40px;color:#999">No products found.</td></tr>';updateInventoryStats()}
function renderPurchases(){const q=(document.getElementById('purchaseSearch')?.value||'').toLowerCase(),month=document.getElementById('purchaseDateFilter')?.value||'',tbody=document.getElementById('purchaseTable');if(!tbody)return;let arr=getPurchases().filter(p=>(!q||String(p.product).toLowerCase().includes(q))&&(!month||String(p.date).slice(0,7)===month)).sort((a,b)=>new Date(b.date)-new Date(a.date));tbody.innerHTML=arr.length?arr.map(p=>`<tr><td>${escapeHTML(p.date||'')}</td><td>${escapeHTML(p.product||'')}</td><td>${Number(p.qty||0)}</td><td>${money(p.price)}</td><td>${money(Number(p.qty||0)*Number(p.price||0))}</td><td>${escapeHTML(p.supplier||'-')}</td><td><button class="secondary-btn" onclick="deletePurchase('${escapeJS(p.id)}')">🗑️</button></td></tr>`).join(''):'<tr><td colspan="7" style="text-align:center;padding:40px;color:#999">No purchases found.</td></tr>'}
function renderMovements(){const type=document.getElementById('movementTypeFilter')?.value||'all',month=document.getElementById('movementDateFilter')?.value||'',tbody=document.getElementById('movementTable');if(!tbody)return;let arr=getLedger().slice().reverse().filter(m=>(type==='all'||m.type===type)&&(!month||String(m.date).slice(0,7)===month));tbody.innerHTML=arr.length?arr.map(m=>`<tr><td>${new Date(m.date).toLocaleString('en-IN')}</td><td>${escapeHTML(m.type||'')}</td><td>${escapeHTML(m.inventoryKey||'')}</td><td>${Number(m.quantity||0)}</td><td>${Number(m.before||0)}</td><td>${Number(m.after||0)}</td><td>${escapeHTML(m.reference||m.billNumber||'-')}</td></tr>`).join(''):'<tr><td colspan="7" style="text-align:center;padding:40px;color:#999">No stock movement found.</td></tr>'}
function updateInventoryStats(){const inv=readInventory(),entries=Object.entries(inv);document.getElementById('productCount').textContent=entries.length;const low=entries.filter(([,r])=>Number(r.reorderLevel??r.minStock??0)>0&&getStock(r)<=Number(r.reorderLevel??r.minStock));document.getElementById('lowStockCount').textContent=low.length;document.getElementById('stockValue').textContent=money(entries.reduce((s,[,r])=>s+getStock(r)*Number(r.cost||r.price||0),0));const month=new Date().toISOString().slice(0,7);document.getElementById('purchaseValue').textContent=money(getPurchases().filter(p=>String(p.date).slice(0,7)===month).reduce((s,p)=>s+Number(p.qty||0)*Number(p.price||0),0))}
function adjustStock(key){if(typeof hasPermission==='function'&&!hasPermission('inventory.manage'))return alert('You do not have permission to manage inventory.');const inv=readInventory(),r=inv[key],si=stockInfo(r);if(!si)return;const value=prompt(`Current stock: ${si.value}\nEnter adjustment (+/-):`,'0');if(value===null)return;const delta=Number(value);if(!Number.isFinite(delta))return alert('Invalid adjustment.');const before=si.value,after=Math.max(0,before+delta);r[si.field]=after;saveInventory(inv);logMovement({type:'adjustment',inventoryKey:key,quantity:delta,before,after,reference:'Manual Adjustment'});renderProducts();renderMovements();updateInventoryStats()}
function deletePurchase(id){if(typeof hasPermission==='function'&&!hasPermission('inventory.manage'))return alert('You do not have permission to manage inventory.');if(!confirm('Delete this purchase? Stock will be reversed.'))return;const arr=getPurchases(),p=arr.find(x=>String(x.id)===String(id));if(!p)return;const inv=readInventory(),key=findKey(inv,p.product);if(key){const si=stockInfo(inv[key]);if(si){const before=si.value,after=Math.max(0,before-Number(p.qty||0));inv[key][si.field]=after;saveInventory(inv);logMovement({type:'adjustment',inventoryKey:key,quantity:-Number(p.qty||0),before,after,reference:'Purchase Deleted'})}}savePurchases(arr.filter(x=>String(x.id)!==String(id)));renderPurchases();renderProducts();renderMovements();updateInventoryStats()}
function escapeHTML(v){return String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;')}
function escapeJS(v){return String(v??'').replace(/\\/g,'\\\\').replace(/'/g,"\\'")}
document.addEventListener('DOMContentLoaded',()=>{const pf=document.getElementById('productForm');pf?.addEventListener('submit',e=>{e.preventDefault();const name=productName.value.trim();if(!name)return;const inv=readInventory(),key=productKey.value.trim()||name,existing=inv[key]||{};const old=getStock(existing);inv[key]={...existing,category:productCategory.value.trim(),unit:productUnit.value.trim(),stock:Number(productStock.value)||0,reorderLevel:Number(productReorder.value)||0,cost:Number(productCost.value)||0};saveInventory(inv);if(old!==(Number(productStock.value)||0))logMovement({type:'adjustment',inventoryKey:key,quantity:(Number(productStock.value)||0)-old,before:old,after:Number(productStock.value)||0,reference:'Product Save'});closeProductModal();renderProducts();renderMovements();updateInventoryStats()});const pur=document.getElementById('purchaseForm');pur?.addEventListener('submit',e=>{e.preventDefault();const product=purchaseProduct.value,qty=Number(purchaseQty.value),price=Number(purchasePrice.value),date=purchaseDate.value;if(!product||qty<=0||price<0||!date)return alert('Enter valid purchase details.');const inv=readInventory(),key=findKey(inv,product);if(!key)return alert('Product not found.');const si=stockInfo(inv[key]);if(!si)return alert('Selected product has no numeric stock field.');const before=si.value,after=before+qty;inv[key][si.field]=after;inv[key].cost=price;saveInventory(inv);const p={id:'PUR-'+Date.now(),product:key,qty,price,date,supplier:purchaseSupplier.value.trim(),invoiceNo:purchaseInvoice.value.trim(),notes:purchaseNotes.value.trim()};const arr=getPurchases();arr.push(p);savePurchases(arr);logMovement({type:'purchase',inventoryKey:key,quantity:qty,before,after,reference:p.invoiceNo||p.id});closePurchaseModal();renderPurchases();renderProducts();renderMovements();updateInventoryStats()});renderProducts();renderPurchases();renderMovements();updateInventoryStats()});
window.openInventoryTab=openInventoryTab;window.openProductModal=openProductModal;window.closeProductModal=closeProductModal;window.openPurchaseModal=openPurchaseModal;window.closePurchaseModal=closePurchaseModal;window.renderProducts=renderProducts;window.renderPurchases=renderPurchases;window.renderMovements=renderMovements;window.adjustStock=adjustStock;window.deletePurchase=deletePurchase;window.getPOSPurchases=getPurchases;window.getPOSInventoryLedger=getLedger;
})();
